{
  "name": "{{ .Config.GetOrDefault "cleanupPolicyConfiguration/policyName" "ces-maven-snapshot-cleanuppolicy"}}",
  "notes": "{{ .Config.GetOrDefault "cleanupPolicyConfiguration/notes" "default policy that is generated by the ces via a script on nexus startup"}}",
  "mode": "{{ .Config.GetOrDefault "cleanupPolicyConfiguration/mode" "deletion"}}",
  "format": "{{ .Config.GetOrDefault "cleanupPolicyConfiguration/policyFormat" "maven2"}}",
  "criteria": {
    "regex": "{{ .Config.GetOrDefault "cleanupPolicyConfiguration/policyCriteria/regex" ".*SNAPSHOT"}}",
    "criteriaReleaseType": "{{ .Config.GetOrDefault "cleanupPolicyConfiguration/policyCriteria/criteriaReleaseType" "PRERELEASES"}}",
    "criteriaLastBlobUpdated": "{{ .Config.GetOrDefault "cleanupPolicyConfiguration/policyCriteria/criteriaLastBlobUpdated" "14"}}"
  }
}