apiVersion: v2
name: nexus
description: Sonatype Nexus Repository Manager as a Cloudogu EcoSystem Dogu (V3)
type: application
version: 3.86.2-7
appVersion: "3.86.2-01"
icon: https://cloudogu.com/images/dogus/nexus.png
annotations:
  dogu.cloudogu.com/api-version: v3
  dogu.cloudogu.com/application.postgresql: "14.18"
