# Nexus data volume. Holds the Nexus work dir (/var/lib/nexus) and the writable doguctl local config (/var/ces/config).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexus.fullname" . }}-data
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    {{- include "nexus.backupLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.nexus.persistence.storageClassName }}
  storageClassName: {{ .Values.nexus.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.nexus.persistence.size }}
